### ISSUE TITLE
MBR_PRELOAD_ADDR has broken logic

### ISSUE THREAD

**Issue by SiarheiVolkau** [pcercuei/UBIBoot#11]
at least for dual MMC devices, because it reuse preloaded MBR as MBR for both slots.
Moreover, in general we must have no assumptions that UBIBoot loaded from MMC0 and MBR is loaded too,
because it limits area of usages.
As of me, I often load normal (not stage1) UBIboot binaries over USB (jzboot). However, my boards don't use `MBR_PRELOAD_ADDR`.

**Comment by pcercuei** [comment]
Could you send a PR to remove MBR_PRELOAD_ADDR then? With the commit explaining why it was broken.
