### ISSUE TITLE
question about the register base address

### ISSUE THREAD

**Issue by cheng3100** [pcercuei/UBIBoot#13]
From what I read from the programming guide of the jz4725 soc. The register base address should begin from 0x10000000, But from the code I found all register base are from 0xB0000000 which seems has a 0xA0000000 offset. Did I miss some thing? 
![image](https://user-images.githubusercontent.com/25582840/199674186-d3ba9e4f-6151-4d6d-9221-726292bdfddc.png)

**Comment by pcercuei** [comment]
@cheng3100 sorry for the late reply. I get too many work-related notifications on github so I miss the important ones...

Have a look at: https://johnloomis.org/microchip/pic32/memory/memory.html
